### ISSUE TITLE
Memory graphs should contain amount of active memory

### ISSUE THREAD

**Issue by zhuyifei1999** [wikimedia/nagf#7]
Right now the memory graphs is not very useful in telling how much memory is actively used by current processes to store their temporary data:

Inactive - belongs to exited processes, in order to speed restarts
Cached & Buffers - speeds up disk IO
Free - wasted memory that has basically nothing in them
SwapCached - the virtual memory on hard disk

**Comment by Krinkle** [comment]
Thanks! Active memory was indeed missing.

Note that `mem.Active` is a group/alias which mostly contains `mem.Buffers` and `mem.Cached`, but there is indeed more in there.

Worse, the currently included `mem.Inactive` includes things already included in this graph, which is why until now the total was below the top of the stacked graph.

Before:
![graphite wmflabs](https://cloud.githubusercontent.com/assets/156867/13821809/0dafc91a-eb9b-11e5-8bd6-81953da1e936.png)

After:
![graphite wmflabs-1](https://cloud.githubusercontent.com/assets/156867/13821803/08038592-eb9b-11e5-98c4-1c1cd4aa1e02.png)


<http://blog.famzah.net/2014/09/22/know-your-linux-memory-usage/>
